services:
  pypsa_gemspy:
    build:
      context: ..
      dockerfile: docker-tuto-pypsa-gems/Dockerfile_PyPSA_GemsPy
      network: host
    image: my-pypsa-gemspy-tuto
    container_name: my-pypsa-gemspy-tuto
    network_mode: host
    volumes:
      - ../pypsa-eur/resources:/workspace/pypsa-eur/resources:ro

volumes: {}
